blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy

app_name = "blog"

urlpatterns = [
    path('', views.home, name='home'),
    path('book/', views.list_book, name='list_book'),
    path('book/<int:id>/', views.detail_book, name='detail_book'),
    path('book/<int:book_id>/comment', views.comment_book, name='comment_book'),
    path('ticket/', views.ticket, name='ticket'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about_project, name='about'),
    path('help/', views.project_help, name='help'),
    path('terms/', views.terms_of_use, name='terms'),
    path('my_books/', views.my_library, name='my_books'),
    path('download/<int:book_id>/', views.download_book, name='download_book'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('password-change/', auth_view.PasswordChangeView.as_view(
        template_name='blog/password_change_form.html', success_url='/password-change/done/'), name='password_change'),
    path('password-change/done/', auth_view.PasswordChangeDoneView.as_view(
        template_name='blog/password_change_done.html'), name='password_change_done'),
    path('password-reset/', views.password_reset_request_view, name='password_reset'),
    path('password-reset/done/', views.password_reset_done_view, name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('password-reset/complete/', views.password_reset_complete_view, name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('user_edit/', views.user_edit, name="user_edit")
]

book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django_resized import ResizedImageField
from django.dispatch import receiver


class Book(models.Model):
    class Genre(models.TextChoices):
        drama = 'drama', 'drama'
        sci_fi = 'sci-fi', 'sci-fi'
        romance = 'romance', 'romance'
        mystery = 'mystery', 'mystery'
        history = 'history', 'history'
        scientific = 'scientific', 'scientific'
        other = 'other', 'other'

    user_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_book')
    slug = models.SlugField(max_length=250)
    title = models.CharField(max_length=250)
    description = models.TextField()
    num_pages = models.PositiveIntegerField()
    author = models.CharField(max_length=250)
    publisher = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    language = models.CharField(max_length=250)
    file = models.FileField(upload_to='books/files/', blank=True, null=True)
    choices_genre = models.CharField(max_length=25, choices=Genre.choices, default=Genre.other)
    publish = models.DateField(blank=True, null=True, default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.title

    def get_absolut_url(self):
        return reverse('blog:detail_book', args=[self.id])


class Ticket(models.Model):
    name = models.CharField(max_length=250)
    family = models.CharField(max_length=250)
    massage = models.TextField()
    email = models.EmailField(max_length=250)
    subject = models.CharField(max_length=250)
    objects = models.Manager()

    def __str__(self):
        return self.name


class Comment(models.Model):
    book = models.ForeignKey(Book, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    objects = models.Manager()

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name


def image_upload(instance, filename):
    create_year = timezone.now().year
    return f'image_book/{create_year}/{filename}'


class Image(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='images')
    name = models.CharField(max_length=250, blank=True, null=True)
    description = models.CharField(max_length=300, blank=True, null=True)
    image = ResizedImageField(upload_to=image_upload, size=[350, 200], crop=['middle', 'center'], quality=85)
    created = models.DateField(auto_now_add=True)
    objects = models.Manager()

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name


@receiver(post_delete, sender=Image)
def delete_image_file(sender, instance, **kwargs):
    if instance.image:
        instance.image.delete(save=False)


@receiver(post_delete, sender=Book)
def delete_book_images(sender, instance, **kwargs):
    for image in instance.images.all():
        image.delete()


class DownloadedBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='downloaded_books')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='downloads')
    downloaded_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

    class Meta:
        unique_together = ('user', 'book')

    def __str__(self):
        return f"{self.user.username} -> {self.book.title}"


def image_upload_account(instance, filename):
    create_year = timezone.now().year
    return f'image_account/{create_year}/{filename}'


class Account(models.Model):
    user = models.OneToOneField(User, related_name='account', on_delete=models.CASCADE)
    bio = models.TextField()
    birth = models.DateField(blank=True, null=True)
    job = models.CharField(blank=True, null=True)
    photos = ResizedImageField(upload_to=image_upload_account, size=[500, 500], crop=['middle', 'center'], quality=90)
    objects = models.Manager()

    def __str__(self):
        return self.user.username

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import *
from .forms import *
import random
from django.shortcuts import get_object_or_404
from django.http import FileResponse, Http404
from django.contrib.auth.decorators import login_required
import os
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .forms import PasswordResetRequestForm, SetNewPasswordForm
from django.shortcuts import render
from django.contrib.auth.tokens import default_token_generator as token_generator
import random


token_generator = PasswordResetTokenGenerator()


def home(request):
    offers = Book.objects.order_by('?')[:3]
    return render(request, 'blog/home.html', {'offers': offers})


def list_book(request):
    all_book = Book.objects.all()
    paginator = Paginator(all_book, 3)
    num_paginator = request.GET.get('page', 1)
    try:
        all_book = paginator.page(num_paginator)
    except EmptyPage:
        all_book = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        all_book = paginator.page(1)
    return render(request, 'blog/list_book.html', {'all_book': all_book})


def detail_book(request, id):
    book = get_object_or_404(Book, id=id)
    form = CommentForm()
    comment = book.comments.filter(active=True)
    context = {
        'book': book,
        'form': form,
        'comment': comment
    }
    return render(request, 'blog/detail_book.html', context)


def ticket(request):
    if request.method == "POST":
        form = TicketForms(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            ticket_obj = Ticket.objects.create()
            ticket_obj.name = cd["name"]
            ticket_obj.family = cd["family"]
            ticket_obj.massage = cd["massage"]
            ticket_obj.email = cd["email"]
            ticket_obj.subject = cd["subject"]
            ticket_obj.save()
            return redirect('blog:home')
    else:
        form = TicketForms()
    return render(request, 'forms/ticket.html', {'form': form})


@require_POST
def comment_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.book = book
        comment.save()
    context = {
        'book': book,
        'comment': comment,
        'form': form
    }
    return render(request, 'forms/comment.html', context)


def search(request):
    query = None
    result = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            result = result = Book.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).distinct()
    context = {
        'query': query,
        'result': result,
    }
    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    context = {
        'user': user,
        'email': user.email,
        'last_name': user.last_name,
        'first_name': user.first_name,
        'last_login': user.last_login,
        'date_joined': user.date_joined

    }
    return render(request, 'blog/profile.html', context)


def about_project(request):
    return render(request, 'blog/about.html')


def project_help(request):
    return render(request, 'blog/Help.html')


def terms_of_use(request):
    return render(request, 'blog/terms.html')


@login_required
def my_library(request):
    books = DownloadedBook.objects.filter(user=request.user).select_related('book')
    return render(request, 'forms/my_books.html', {'books': books})


@login_required
def download_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    from .models import DownloadedBook
    DownloadedBook.objects.get_or_create(user=request.user, book=book)
    if book.file and os.path.exists(book.file.path):
        return FileResponse(open(book.file.path, 'rb'), as_attachment=True)
    else:
        raise Http404("File not found")


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd["username"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile')
                else:
                    return HttpResponse("Your account is disabled")
            else:
                return HttpResponse("You are not logged in")
    else:
        form = LoginForm()
    return render(request, 'forms/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('blog:home')


def password_reset_request_view(request):
    if request.method == 'POST':
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = None
            if user:
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = token_generator.make_token(user)
                reset_path = reverse('blog:password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
                reset_url = request.build_absolute_uri(reset_path)
                send_mail(
                    'Password Reset',
                    f'Click here to reset your password: {reset_url}',
                    'from@example.com',
                    [email],
                    fail_silently=False,
                )
            return redirect('blog:password_reset_done')
    else:
        form = PasswordResetRequestForm()
    return render(request, 'partials/password_reset_form.html', {'form': form})


def password_reset_confirm_view(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (User.DoesNotExist, ValueError, TypeError):
        user = None

    validlink = False
    if user is not None and token_generator.check_token(user, token):
        validlink = True
        if request.method == 'POST':
            form = SetNewPasswordForm(request.POST)
            if form.is_valid():
                user.set_password(form.cleaned_data['new_password'])
                user.save()
                return redirect('blog:password_reset_complete')
        else:
            form = SetNewPasswordForm()
        return render(request, 'partials/password_reset_confirm.html', {'form': form, 'validlink': validlink})
    else:
        return render(request, 'partials/password_reset_confirm.html', {'validlink': validlink})


def password_reset_done_view(request):
    return render(request, 'partials/password_reset_done.html')


def password_reset_complete_view(request):
    return render(request, 'partials/password_reset_complete.html')


def register(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'partials/congratulations.html', {'user': user})
    else:
        form = UserRegister()
    return render(request, 'partials/register.html', {'form': form})


def user_edit(request):
    try:
        account = request.user.account
    except ObjectDoesNotExist:
        account = Account.objects.create(user=request.user)

    if request.method == "POST":
        form = UserEdit(request.POST, instance=request.user)
        account_form = AccountEdit(request.POST, request.FILES, instance=account)
        if form.is_valid() and account_form.is_valid():
            form.save()
            account_form.save()
            return redirect('/')

    else:
        form = UserEdit(instance=request.user)
        account_form = AccountEdit(instance=account)

    context = {
        'user_form': form,
        'account_form': account_form,
        'account': account,
    }
    return render(request, 'partials/edit_information.html', context)

blog/templates/partials/congratulations.html
{% extends 'parent/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<style>
  .register-success-box {
    max-width: 400px;
    margin: 80px auto;
    padding: 40px 30px;
    background: #f0f9ff;
    border-radius: 14px;
    box-shadow: 0 10px 30px rgba(0, 123, 204, 0.2);
    text-align: center;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #034078;
  }

  .welcome-title {
    font-size: 1.8rem;
    margin-bottom: 15px;
    font-weight: 700;
  }

  .success-message {
    font-size: 1.1rem;
    margin-bottom: 30px;
    color: #0366d6;
  }

  .login-button {
    display: inline-block;
    padding: 12px 35px;
    background-color: #007acc;
    color: white;
    text-decoration: none;
    font-weight: 600;
    border-radius: 10px;
    box-shadow: 0 5px 15px rgba(0, 122, 204, 0.3);
    transition: background-color 0.3s ease, box-shadow 0.3s ease;
  }

  .login-button:hover {
    background-color: #005fa3;
    box-shadow: 0 7px 20px rgba(0, 95, 163, 0.5);
  }
</style>

<div class="register-success-box">
  <h3 class="welcome-title">Welcome, {{ user }}</h3>
  <p class="success-message">Your registration was successful.</p>
  <a href="{% url 'blog:login' %}" class="login-button">Login</a>
</div>
{% endblock %}

blog/templates/partials/edit_information.html
{% extends 'parent/base.html' %}

{% block title %}Edit Account{% endblock %}

{% block content %}
<style>
  .form {
    max-width: 600px;
    margin: 30px auto;
    padding: 30px 25px;
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.1);
    font-family: Tahoma, Geneva, Verdana, sans-serif;
    direction: ltr;
    color: #333;
  }

  h4 {
    font-weight: 700;
    color: #007acc;
    margin-bottom: 20px;
    border-bottom: 2px solid #007acc;
    padding-bottom: 6px;
  }

  .form-group {
    margin-bottom: 18px;
  }

  label {
    display: block;
    margin-bottom: 8px;
    font-weight: 600;
    color: #444;
  }

  input[type="text"],
  input[type="email"],
  input[type="date"],
  textarea {
    width: 100%;
    padding: 10px 14px;
    border: 1.8px solid #ccc;
    border-radius: 8px;
    font-size: 1rem;
    transition: border-color 0.3s ease;
    font-family: inherit;
    resize: vertical;
  }
  input[type="text"]:focus,
  input[type="email"]:focus,
  input[type="date"]:focus,
  textarea:focus {
    border-color: #007acc;
    outline: none;
  }

  img {
    border-radius: 10px;
    margin-top: 8px;
    max-width: 100px;
    height: auto;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.08);
  }

  .btn-primary {
    background-color: #007acc;
    color: #fff;
    font-weight: 600;
    padding: 12px 25px;
    border: none;
    border-radius: 10px;
    cursor: pointer;
    transition: background-color 0.3s ease;
    width: 100%;
    font-size: 1.1rem;
  }
  .btn-primary:hover {
    background-color: #005a99;
  }

  hr {
    border: none;
    border-bottom: 1.5px solid #ddd;
    margin: 25px 0;
  }

  /* Responsive */
  @media (max-width: 650px) {
    .form {
      padding: 20px 15px;
      margin: 15px;
    }
  }
</style>

<form method="POST" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    <h4>User Information</h4>

    <div class="form-group">
        <label for="id_first_name">First Name</label>
        <input type="text" name="first_name" id="id_first_name" class="form-control"
               value="{{ user_form.first_name.value|default_if_none:'' }}">
    </div>

    <div class="form-group">
        <label for="id_last_name">Last Name</label>
        <input type="text" name="last_name" id="id_last_name" class="form-control"
               value="{{ user_form.last_name.value|default_if_none:'' }}">
    </div>

    <div class="form-group">
        <label for="id_email">Email</label>
        <input type="email" name="email" id="id_email" class="form-control"
               value="{{ user_form.email.value|default_if_none:'' }}">
    </div>

    <hr>

    <h4>Account Information</h4>

    <div class="form-group">
        <label for="id_bio">Biography</label>
        <textarea name="bio" id="id_bio" class="form-control" rows="4">{{ account_form.bio.value|default_if_none:'' }}</textarea>
    </div>

    <div class="form-group">
        <label for="id_birth">Date of Birth</label>
        <input type="date" name="birth" id="id_birth" class="form-control"
               value="{{ account_form.birth.value|date:'Y-m-d' }}">
    </div>

    <div class="form-group">
        <label for="id_job">Job</label>
        <input type="text" name="job" id="id_job" class="form-control"
               value="{{ account_form.job.value|default_if_none:'' }}">
    </div>

    <div class="form-group">
        <label for="id_photos">Profile Picture</label><br>
        {% if account_form.instance.photos %}
            <img src="{{ account_form.instance.photos.url }}" alt="Profile Photo"><br>
        {% endif %}
        {{ account_form.photos }}
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

blog/templates/partials/header.html
<nav style="
    display: flex;
    justify-content: space-between;
    align-items: center;
    background: linear-gradient(to right, #007BFF, #00BFFF);
    padding: 15px 25px;
    border-radius: 12px;
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
    flex-wrap: wrap;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
">
    <div style="display: flex; gap: 20px; flex-wrap: wrap; align-items: center;">
        {% csrf_token %}
        <a class="a_nav" href="{% url 'blog:home' %}" style="
            color: white;
            text-decoration: none;
            font-weight: 600;
            padding: 8px 16px;
            border-radius: 8px;
            transition: background 0.3s ease;
        " onmouseover="this.style.background='rgba(255,255,255,0.2)'" onmouseout="this.style.background='transparent'">Home</a>

        <a class="a_nav" href="{% url 'blog:list_book' %}" style="
            color: white;
            text-decoration: none;
            font-weight: 600;
            padding: 8px 16px;
            border-radius: 8px;
            transition: background 0.3s ease;
        " onmouseover="this.style.background='rgba(255,255,255,0.2)'" onmouseout="this.style.background='transparent'">Book</a>

        <a class="a_nav" href="{% url 'blog:ticket' %}" style="
            color: white;
            text-decoration: none;
            font-weight: 600;
            padding: 8px 16px;
            border-radius: 8px;
            transition: background 0.3s ease;
        " onmouseover="this.style.background='rgba(255,255,255,0.2)'" onmouseout="this.style.background='transparent'">Ticket</a>

        {% if user.is_authenticated %}
            <a class="a_nav" href="{% url 'blog:profile' %}" style="
                color: white;
                text-decoration: none;
                font-weight: 600;
                padding: 8px 16px;
                border-radius: 8px;
                transition: background 0.3s ease;
            " onmouseover="this.style.background='rgba(255,255,255,0.2)'" onmouseout="this.style.background='transparent'">Profile</a>
        {% endif %}
    </div>

    <div style="display: flex; gap: 15px; align-items: center; flex-wrap: wrap; margin-top: 10px;">
        {% if user.is_authenticated %}
            <span style="color: white; font-weight: 500;">👋 Hello, {{ user.username }}</span>
            <a href="{% url 'blog:logout' %}" style="
                background: #ff4d4d;
                color: white;
                padding: 8px 16px;
                text-decoration: none;
                border-radius: 8px;
                font-weight: bold;
                transition: background 0.3s ease;
            " onmouseover="this.style.background='#cc0000'" onmouseout="this.style.background='#ff4d4d'">Logout</a>
        {% else %}
            <a href="{% url 'blog:login' %}" style="
                background: white;
                color: #007BFF;
                padding: 8px 16px;
                text-decoration: none;
                border-radius: 8px;
                font-weight: bold;
                transition: background 0.3s ease;
            " onmouseover="this.style.background='#f0f0f0'" onmouseout="this.style.background='white'">Login</a>

            <a href="{% url 'blog:register' %}" style="
                background: #28a745;
                color: white;
                padding: 8px 16px;
                text-decoration: none;
                border-radius: 8px;
                font-weight: bold;
                transition: background 0.3s ease;
            " onmouseover="this.style.background='#218838'" onmouseout="this.style.background='#28a745'">Signup</a>
        {% endif %}
    </div>
</nav>
<br>

blog/templates/partials/paginator.html
<style>
.pagination {
  display: flex;
  justify-content: center;
  gap: 15px;
  margin: 30px 0;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.pagination-btn {
  padding: 10px 20px;
  background-color: #007acc;
  color: white;
  border-radius: 8px;
  text-decoration: none;
  font-weight: 600;
  box-shadow: 0 4px 12px rgba(0, 122, 204, 0.4);
  transition: background-color 0.3s ease, transform 0.2s ease, box-shadow 0.3s ease;
  user-select: none;
}

.pagination-btn:hover,
.pagination-btn:focus {
  background-color: #005a99;
  box-shadow: 0 6px 16px rgba(0, 90, 153, 0.6);
  transform: scale(1.05);
  outline: none;
}

.pagination-btn:active {
  transform: scale(0.98);
  box-shadow: 0 3px 8px rgba(0, 90, 153, 0.7);
}

</style>

<div class="pagination">
  {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}" class="pagination-btn" aria-label="صفحه قبلی">Previous</a>
  {% endif %}

  {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" class="pagination-btn" aria-label="صفحه بعدی">Next</a>
  {% endif %}
</div>

blog/templates/partials/password_reset_complete.html
{% extends 'parent/base.html' %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<style>
  .success-container {
    max-width: 400px;
    margin: 100px auto;
    padding: 40px 30px;
    background: #e8f5e9;
    border-radius: 15px;
    box-shadow: 0 8px 30px rgba(46, 125, 50, 0.3);
    text-align: center;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #2e7d32;
    position: relative;
    overflow: visible;
  }

  .success-container h3 {
    font-size: 2rem;
    margin-bottom: 15px;
    font-weight: 700;
  }

  .success-container p {
    font-size: 1.1rem;
    margin-bottom: 25px;
  }

  .success-container a {
    color: white;
    background-color: #43a047;
    padding: 12px 30px;
    border-radius: 12px;
    text-decoration: none;
    font-weight: 600;
    box-shadow: 0 5px 15px rgba(67, 160, 71, 0.4);
    transition: background-color 0.3s ease;
  }
  .success-container a:hover {
    background-color: #2e7d32;
  }

  /* Confetti pieces */
  .confetti-piece {
    position: absolute;
    top: -10px;
    width: 10px;
    height: 10px;
    background-color: var(--color);
    left: var(--left);
    opacity: 0;
    border-radius: 3px;
    animation-name: fall;
    animation-timing-function: ease-in;
    animation-iteration-count: infinite;
    animation-delay: var(--delay);
    animation-duration: var(--duration);
  }

  @keyframes fall {
    0% {
      opacity: 1;
      transform: translateY(0) rotate(0deg);
    }
    100% {
      opacity: 0;
      transform: translateY(250px) rotate(360deg);
    }
  }
</style>

<div class="success-container">
  <h3>Reset Password</h3>
  <p>Password changed successfully.</p>
  <p><a href="{% url 'blog:login' %}">Login</a></p>

  <!-- confetti elements -->
  <div class="confetti-piece" style="--left: 5%; --delay: 0s; --duration: 4s; --color: #e74c3c;"></div>
  <div class="confetti-piece" style="--left: 15%; --delay: 1s; --duration: 5.2s; --color: #f1c40f;"></div>
  <div class="confetti-piece" style="--left: 25%; --delay: 0.7s; --duration: 4.8s; --color: #3498db;"></div>
  <div class="confetti-piece" style="--left: 35%; --delay: 0.3s; --duration: 6.1s; --color: #2ecc71;"></div>
  <div class="confetti-piece" style="--left: 45%; --delay: 1.2s; --duration: 5.5s; --color: #9b59b6;"></div>
  <div class="confetti-piece" style="--left: 55%; --delay: 0.4s; --duration: 4.4s; --color: #e67e22;"></div>
  <div class="confetti-piece" style="--left: 62%; --delay: 0.9s; --duration: 5.8s; --color: #1abc9c;"></div>
  <div class="confetti-piece" style="--left: 70%; --delay: 0.2s; --duration: 6.3s; --color: #34495e;"></div>
  <div class="confetti-piece" style="--left: 78%; --delay: 1.1s; --duration: 5.1s; --color: #8e44ad;"></div>
  <div class="confetti-piece" style="--left: 85%; --delay: 0.6s; --duration: 4.6s; --color: #27ae60;"></div>
  <div class="confetti-piece" style="--left: 92%; --delay: 1.3s; --duration: 5.3s; --color: #c0392b;"></div>
  <div class="confetti-piece" style="--left: 98%; --delay: 0.8s; --duration: 6s; --color: #2980b9;"></div>
</div>
{% endblock %}

blog/templates/partials/password_reset_done.html
{% extends 'parent/base.html' %}

{% block content %}
<div class="confirmation-container">
  <h3>Reset Password</h3>
  <p>A password change link has been sent to you. Please check your email.</p>
</div>
{% endblock %}