blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy

app_name = "blog"

urlpatterns = [
    path('', views.home, name='home'),
    path('book/', views.list_book, name='list_book'),
    path('book/<int:id>/', views.detail_book, name='detail_book'),
    path('book/<int:book_id>/comment', views.comment_book, name='comment_book'),
    path('ticket/', views.ticket, name='ticket'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about_project, name='about'),
    path('help/', views.project_help, name='help'),
    path('terms/', views.terms_of_use, name='terms'),
    path('my_books/', views.my_library, name='my_books'),
    path('download/<int:book_id>/', views.download_book, name='download_book'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('password-change/', auth_view.PasswordChangeView.as_view(
        template_name='blog/password_change_form.html', success_url='/password-change/done/'), name='password_change'),
    path('password-change/done/', auth_view.PasswordChangeDoneView.as_view(
        template_name='blog/password_change_done.html'), name='password_change_done'),
    path('password-reset/', views.password_reset_request_view, name='password_reset'),
    path('password-reset/done/', views.password_reset_done_view, name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('password-reset/complete/', views.password_reset_complete_view, name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('user_edit/', views.user_edit, name="user_edit")
]

book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import *


class TicketForms(forms.Form):
    SUBJECT_CHOICE = (
        ('Offer', 'Offer'),
        ('Report', 'Report'),
        ('Criticism', 'Criticism'),
    )
    name = forms.CharField(max_length=250, required=True)
    family = forms.CharField(max_length=250, required=True)
    massage = forms.CharField(widget=forms.Textarea, required=True)
    email = forms.EmailField(max_length=250, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICE, required=True)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField()


class SetNewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned = super().clean()
        if cleaned.get('new_password') != cleaned.get('confirm_password'):
            raise forms.ValidationError("Passwords do not match")
        return cleaned


class UserRegister(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, max_length=20, required=True, label='password')
    password2 = forms.CharField(widget=forms.PasswordInput, max_length=20, required=True, label='repeat password')

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data


class UserEdit(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class AccountEdit(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['bio', 'birth', 'job', 'photos']

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import *
from .forms import *
import random
from django.shortcuts import get_object_or_404
from django.http import FileResponse, Http404
from django.contrib.auth.decorators import login_required
import os
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .forms import PasswordResetRequestForm, SetNewPasswordForm
from django.shortcuts import render
from django.contrib.auth.tokens import default_token_generator as token_generator
import random


token_generator = PasswordResetTokenGenerator()


def home(request):
    offers = Book.objects.order_by('?')[:3]
    return render(request, 'blog/home.html', {'offers': offers})


def list_book(request):
    all_book = Book.objects.all()
    paginator = Paginator(all_book, 3)
    num_paginator = request.GET.get('page', 1)
    try:
        all_book = paginator.page(num_paginator)
    except EmptyPage:
        all_book = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        all_book = paginator.page(1)
    return render(request, 'blog/list_book.html', {'all_book': all_book})


def detail_book(request, id):
    book = get_object_or_404(Book, id=id)
    form = CommentForm()
    comment = book.comments.filter(active=True)
    context = {
        'book': book,
        'form': form,
        'comment': comment
    }
    return render(request, 'blog/detail_book.html', context)


def ticket(request):
    if request.method == "POST":
        form = TicketForms(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            ticket_obj = Ticket.objects.create()
            ticket_obj.name = cd["name"]
            ticket_obj.family = cd["family"]
            ticket_obj.massage = cd["massage"]
            ticket_obj.email = cd["email"]
            ticket_obj.subject = cd["subject"]
            ticket_obj.save()
            return redirect('blog:home')
    else:
        form = TicketForms()
    return render(request, 'forms/ticket.html', {'form': form})


@require_POST
def comment_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.book = book
        comment.save()
    context = {
        'book': book,
        'comment': comment,
        'form': form
    }
    return render(request, 'forms/comment.html', context)


def search(request):
    query = None
    result = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            result = result = Book.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).distinct()
    context = {
        'query': query,
        'result': result,
    }
    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    context = {
        'user': user,
        'email': user.email,
        'last_name': user.last_name,
        'first_name': user.first_name,
        'last_login': user.last_login,
        'date_joined': user.date_joined

    }
    return render(request, 'blog/profile.html', context)


def about_project(request):
    return render(request, 'blog/about.html')


def project_help(request):
    return render(request, 'blog/Help.html')


def terms_of_use(request):
    return render(request, 'blog/terms.html')


@login_required
def my_library(request):
    books = DownloadedBook.objects.filter(user=request.user).select_related('book')
    return render(request, 'forms/my_books.html', {'books': books})


@login_required
def download_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    from .models import DownloadedBook
    DownloadedBook.objects.get_or_create(user=request.user, book=book)
    if book.file and os.path.exists(book.file.path):
        return FileResponse(open(book.file.path, 'rb'), as_attachment=True)
    else:
        raise Http404("File not found")


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd["username"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile')
                else:
                    return HttpResponse("Your account is disabled")
            else:
                return HttpResponse("You are not logged in")
    else:
        form = LoginForm()
    return render(request, 'forms/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('blog:home')


def password_reset_request_view(request):
    if request.method == 'POST':
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = None
            if user:
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = token_generator.make_token(user)
                reset_path = reverse('blog:password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
                reset_url = request.build_absolute_uri(reset_path)
                send_mail(
                    'Password Reset',
                    f'Click here to reset your password: {reset_url}',
                    'from@example.com',
                    [email],
                    fail_silently=False,
                )
            return redirect('blog:password_reset_done')
    else:
        form = PasswordResetRequestForm()
    return render(request, 'partials/password_reset_form.html', {'form': form})


def password_reset_confirm_view(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (User.DoesNotExist, ValueError, TypeError):
        user = None

    validlink = False
    if user is not None and token_generator.check_token(user, token):
        validlink = True
        if request.method == 'POST':
            form = SetNewPasswordForm(request.POST)
            if form.is_valid():
                user.set_password(form.cleaned_data['new_password'])
                user.save()
                return redirect('blog:password_reset_complete')
        else:
            form = SetNewPasswordForm()
        return render(request, 'partials/password_reset_confirm.html', {'form': form, 'validlink': validlink})
    else:
        return render(request, 'partials/password_reset_confirm.html', {'validlink': validlink})


def password_reset_done_view(request):
    return render(request, 'partials/password_reset_done.html')


def password_reset_complete_view(request):
    return render(request, 'partials/password_reset_complete.html')


def register(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'partials/congratulations.html', {'user': user})
    else:
        form = UserRegister()
    return render(request, 'partials/register.html', {'form': form})


def user_edit(request):
    try:
        account = request.user.account
    except ObjectDoesNotExist:
        account = Account.objects.create(user=request.user)

    if request.method == "POST":
        form = UserEdit(request.POST, instance=request.user)
        account_form = AccountEdit(request.POST, request.FILES, instance=account)
        if form.is_valid() and account_form.is_valid():
            form.save()
            account_form.save()
            return redirect('/')

    else:
        form = UserEdit(instance=request.user)
        account_form = AccountEdit(instance=account)

    context = {
        'user_form': form,
        'account_form': account_form,
        'account': account,
    }
    return render(request, 'partials/edit_information.html', context)

blog/templates/forms/comment.html
{% extends 'parent/Base.html' %}
{% block title %}Send Comment{% endblock %}

{% block content %}
<div class="success-message-container">
    <div class="success-card">
        <h2 class="success-title">Your comment has been successfully submitted!</h2>
        <p class="success-text">Thank you for your feedback. We appreciate your input.</p>
        <a href="{{book.get_absolut_url}}" class="back-button">Go Back</a>
    </div>
</div>
{% endblock %}

blog/templates/forms/login.html
{% extends 'parent/Base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<style>
  form {
    max-width: 380px;
    margin: 80px auto;
    background: #fff;
    padding: 30px 35px;
    border-radius: 12px;
    box-shadow: 0 12px 25px rgba(0, 0, 0, 0.1);
  }
  /* بقیه استایل‌ها هم همینجا */
  label {
    display: block;
    font-weight: 600;
    color: #34495e;
    margin-bottom: 6px;
    margin-top: 20px;
  }
  input[type="text"],
  input[type="password"] {
    width: 100%;
    padding: 12px 15px;
    font-size: 16px;
    border: 1.8px solid #ccc;
    border-radius: 8px;
    transition: border-color 0.3s ease;
  }
  input[type="text"]:focus,
  input[type="password"]:focus {
    border-color: #2980b9;
    outline: none;
  }
  input[type="submit"] {
    width: 100%;
    padding: 14px;
    margin-top: 25px;
    background-color: #2980b9;
    border: none;
    border-radius: 10px;
    color: white;
    font-weight: 700;
    font-size: 18px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }
  input[type="submit"]:hover {
    background-color: #1f6391;
  }
  a {
    display: inline-block;
    margin-top: 15px;
    color: #2980b9;
    font-weight: 600;
    text-decoration: none;
    transition: color 0.3s ease;
  }
  a:hover {
    color: #1f6391;
    text-decoration: underline;
  }
</style>

<form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" required id="username">

    <label for="password">Password:</label>
    <input type="password" name="password" required id="password">

    <input type="submit" value="Login">

    <a href="{% url 'blog:password_reset' %}">Forgot Password?</a>
</form>
{% endblock %}

blog/templates/forms/my_books.html
{% extends 'parent/Base.html' %}
{% block title %} My Books {% endblock %}

{% block content %}
<style>
  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: #f9fafb;
    color: #333;
  }

  h2 {
    text-align: center;
    color: #007acc;
    margin-bottom: 1.8rem;
    font-weight: 700;
  }

  ul {
    max-width: 700px;
    margin: 0 auto 2rem auto;
    padding: 0;
    list-style: none;
  }

  li {
    background: #fff;
    padding: 18px 25px;
    border-radius: 10px;
    box-shadow: 0 6px 15px rgba(0,0,0,0.05);
    margin-bottom: 16px;
    line-height: 1.4;
    transition: box-shadow 0.3s ease;
  }
  li:hover {
    box-shadow: 0 10px 20px rgba(0,0,0,0.1);
  }

  strong {
    font-size: 1.15rem;
    color: #222;
  }

  .download-link {
    display: inline-block;
    margin-top: 8px;
    margin-right: 15px;
    padding: 8px 16px;
    background-color: #007acc;
    color: white;
    border-radius: 6px;
    text-decoration: none;
    font-weight: 600;
    transition: background-color 0.3s ease;
  }

  .download-link:hover {
    background-color: #005a99;
  }

  p {
    max-width: 600px;
    margin: 1.5rem auto;
    text-align: center;
    font-size: 1.1rem;
    color: #666;
  }

  a.back-link {
    display: block;
    max-width: 120px;
    margin: 0 auto;
    padding: 10px 0;
    background-color: #007acc;
    color: white;
    border-radius: 8px;
    text-align: center;
    font-weight: 600;
    text-decoration: none;
    transition: background-color 0.3s ease;
  }
  a.back-link:hover {
    background-color: #005a99;
  }
</style>

<h2>Downloaded Books</h2>

{% if books %}
    <ul>
        {% for item in books %}
            <li>
                <strong>{{ item.book.title }}</strong> (Author: {{ item.book.author }})
                <br>
                <a href="{% url 'blog:download_book' item.book.id %}" class="download-link">Redownload</a>
                <a href="{{ item.book.file.url }}" class="download-link">Show file</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>You have not downloaded any books yet.</p>
{% endif %}

<a href="{% url 'blog:profile' %}" class="back-link">Back</a>
{% endblock %}

blog/templates/forms/ticket.html
{% extends 'parent/Base.html' %}
{% block title %} Ticket {% endblock %}

{% block content %}
<style>
    /* استایل‌هایی که قبلا دادم */
    body {
        background: #f7f9fc;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #333;
    }
    .form-container {
        max-width: 480px;
        background-color: #ffffff;
        margin: 40px auto;
        padding: 30px 40px;
        border-radius: 15px;
        box-shadow: 0 12px 30px rgba(0, 123, 204, 0.15);
        transition: box-shadow 0.3s ease;
    }
    .form-container:hover {
        box-shadow: 0 16px 40px rgba(0, 123, 204, 0.25);
    }
    .title_ticket {
        text-align: center;
        color: #007acc;
        font-size: 2.2rem;
        margin-bottom: 0.5rem;
        font-weight: 700;
        user-select: none;
    }
    hr {
        border: none;
        border-top: 2px solid #007acc;
        margin: 15px 0 30px 0;
        width: 60px;
        margin-left: auto;
        margin-right: auto;
        border-radius: 3px;
    }
    .form-group {
        margin-bottom: 20px;
        display: flex;
        flex-direction: column;
    }
    label {
        font-weight: 600;
        margin-bottom: 8px;
        color: #444;
        user-select: none;
    }
    input[type="text"],
    input[type="email"],
    select,
    textarea {
        padding: 12px 15px;
        border: 1.8px solid #ccc;
        border-radius: 10px;
        font-size: 1rem;
        transition: border-color 0.3s ease;
        resize: vertical;
        min-height: 40px;
        font-family: inherit;
    }
    input[type="text"]:focus,
    input[type="email"]:focus,
    select:focus,
    textarea:focus {
        border-color: #007acc;
        outline: none;
        box-shadow: 0 0 8px rgba(0, 122, 204, 0.4);
    }
    textarea {
        min-height: 100px;
        font-family: inherit;
    }
    .submit-btn {
        background-color: #007acc;
        color: white;
        font-weight: 700;
        padding: 14px 0;
        border: none;
        border-radius: 12px;
        cursor: pointer;
        font-size: 1.1rem;
        transition: background-color 0.3s ease, transform 0.15s ease;
        user-select: none;
        box-shadow: 0 6px 18px rgba(0, 122, 204, 0.4);
    }
    .submit-btn:hover {
        background-color: #005a99;
        transform: scale(1.05);
        box-shadow: 0 8px 24px rgba(0, 90, 153, 0.6);
    }
    .submit-btn:active {
        transform: scale(0.95);
        box-shadow: 0 4px 12px rgba(0, 90, 153, 0.7);
    }
    .error-section {
        margin-top: 25px;
        background-color: #ffe6e6;
        border: 1px solid #ff4c4c;
        border-radius: 10px;
        padding: 15px 20px;
    }
    .error-message {
        color: #d8000c;
        font-weight: 600;
        margin-bottom: 8px;
        font-size: 0.95rem;
        user-select: none;
    }
    @media (max-width: 520px) {
        .form-container {
            padding: 25px 20px;
            margin: 20px 10px;
        }
    }
</style>

<div class="form-container">
    <form method="post" class="ticket-form">
        {% csrf_token %}
        <h2 class="title_ticket">Ticket</h2>
        <hr>
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" name="name" placeholder="name..." required
                   {% if form.name.value %} value="{{ form.name.value }}" {% endif %}>
        </div>

        <div class="form-group">
            <label for="family">Family:</label>
            <input type="text" name="family" placeholder="family..." required
                   {% if form.family.value %} value="{{ form.family.value }}" {% endif %}>
        </div>

        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" placeholder="email..." required
                   {% if form.email.value %} value="{{ form.email.value }}" {% endif %}>
        </div>

        <div class="form-group">
            <label for="subject">Subject:</label>
            <select name="subject" id="subject">
                <option value="Offer">Offer</option>
                <option value="Criticism">Criticism</option>
                <option value="Report">Report</option>
            </select>
        </div>

        <div class="form-group">
            <label for="massage">Message:</label>
            <textarea name="massage">{% if form.massage.value %}{{ form.massage.value }}{% endif %}</textarea>
        </div>

        <div class="form-group">
            <input type="submit" value="Send" class="submit-btn">
        </div>
    </form>

    {% if form.errors %}
        <div class="error-section">
            {% for fild in form %}
                {% if fild.errors %}
                    {% for error in fild.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}