blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy

app_name = "blog"

urlpatterns = [
    path('', views.home, name='home'),
    path('book/', views.list_book, name='list_book'),
    path('book/<int:id>/', views.detail_book, name='detail_book'),
    path('book/<int:book_id>/comment', views.comment_book, name='comment_book'),
    path('ticket/', views.ticket, name='ticket'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about_project, name='about'),
    path('help/', views.project_help, name='help'),
    path('terms/', views.terms_of_use, name='terms'),
    path('my_books/', views.my_library, name='my_books'),
    path('download/<int:book_id>/', views.download_book, name='download_book'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('password-change/', auth_view.PasswordChangeView.as_view(
        template_name='blog/password_change_form.html', success_url='/password-change/done/'), name='password_change'),
    path('password-change/done/', auth_view.PasswordChangeDoneView.as_view(
        template_name='blog/password_change_done.html'), name='password_change_done'),
    path('password-reset/', views.password_reset_request_view, name='password_reset'),
    path('password-reset/done/', views.password_reset_done_view, name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('password-reset/complete/', views.password_reset_complete_view, name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('user_edit/', views.user_edit, name="user_edit")
]

book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import *


class TicketForms(forms.Form):
    SUBJECT_CHOICE = (
        ('Offer', 'Offer'),
        ('Report', 'Report'),
        ('Criticism', 'Criticism'),
    )
    name = forms.CharField(max_length=250, required=True)
    family = forms.CharField(max_length=250, required=True)
    massage = forms.CharField(widget=forms.Textarea, required=True)
    email = forms.EmailField(max_length=250, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICE, required=True)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField()


class SetNewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned = super().clean()
        if cleaned.get('new_password') != cleaned.get('confirm_password'):
            raise forms.ValidationError("Passwords do not match")
        return cleaned


class UserRegister(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, max_length=20, required=True, label='password')
    password2 = forms.CharField(widget=forms.PasswordInput, max_length=20, required=True, label='repeat password')

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data


class UserEdit(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class AccountEdit(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['bio', 'birth', 'job', 'photos']

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import *
from .forms import *
import random
from django.shortcuts import get_object_or_404
from django.http import FileResponse, Http404
from django.contrib.auth.decorators import login_required
import os
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .forms import PasswordResetRequestForm, SetNewPasswordForm
from django.shortcuts import render
from django.contrib.auth.tokens import default_token_generator as token_generator
import random


token_generator = PasswordResetTokenGenerator()


def home(request):
    offers = Book.objects.order_by('?')[:3]
    return render(request, 'blog/home.html', {'offers': offers})


def list_book(request):
    all_book = Book.objects.all()
    paginator = Paginator(all_book, 3)
    num_paginator = request.GET.get('page', 1)
    try:
        all_book = paginator.page(num_paginator)
    except EmptyPage:
        all_book = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        all_book = paginator.page(1)
    return render(request, 'blog/list_book.html', {'all_book': all_book})


def detail_book(request, id):
    book = get_object_or_404(Book, id=id)
    form = CommentForm()
    comment = book.comments.filter(active=True)
    context = {
        'book': book,
        'form': form,
        'comment': comment
    }
    return render(request, 'blog/detail_book.html', context)


def ticket(request):
    if request.method == "POST":
        form = TicketForms(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            ticket_obj = Ticket.objects.create()
            ticket_obj.name = cd["name"]
            ticket_obj.family = cd["family"]
            ticket_obj.massage = cd["massage"]
            ticket_obj.email = cd["email"]
            ticket_obj.subject = cd["subject"]
            ticket_obj.save()
            return redirect('blog:home')
    else:
        form = TicketForms()
    return render(request, 'forms/ticket.html', {'form': form})


@require_POST
def comment_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.book = book
        comment.save()
    context = {
        'book': book,
        'comment': comment,
        'form': form
    }
    return render(request, 'forms/comment.html', context)


def search(request):
    query = None
    result = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            result = result = Book.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).distinct()
    context = {
        'query': query,
        'result': result,
    }
    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    context = {
        'user': user,
        'email': user.email,
        'last_name': user.last_name,
        'first_name': user.first_name,
        'last_login': user.last_login,
        'date_joined': user.date_joined

    }
    return render(request, 'blog/profile.html', context)


def about_project(request):
    return render(request, 'blog/about.html')


def project_help(request):
    return render(request, 'blog/Help.html')


def terms_of_use(request):
    return render(request, 'blog/terms.html')


@login_required
def my_library(request):
    books = DownloadedBook.objects.filter(user=request.user).select_related('book')
    return render(request, 'forms/my_books.html', {'books': books})


@login_required
def download_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    from .models import DownloadedBook
    DownloadedBook.objects.get_or_create(user=request.user, book=book)
    if book.file and os.path.exists(book.file.path):
        return FileResponse(open(book.file.path, 'rb'), as_attachment=True)
    else:
        raise Http404("File not found")


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd["username"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile')
                else:
                    return HttpResponse("Your account is disabled")
            else:
                return HttpResponse("You are not logged in")
    else:
        form = LoginForm()
    return render(request, 'forms/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('blog:home')


def password_reset_request_view(request):
    if request.method == 'POST':
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = None
            if user:
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = token_generator.make_token(user)
                reset_path = reverse('blog:password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
                reset_url = request.build_absolute_uri(reset_path)
                send_mail(
                    'Password Reset',
                    f'Click here to reset your password: {reset_url}',
                    'from@example.com',
                    [email],
                    fail_silently=False,
                )
            return redirect('blog:password_reset_done')
    else:
        form = PasswordResetRequestForm()
    return render(request, 'partials/password_reset_form.html', {'form': form})


def password_reset_confirm_view(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (User.DoesNotExist, ValueError, TypeError):
        user = None

    validlink = False
    if user is not None and token_generator.check_token(user, token):
        validlink = True
        if request.method == 'POST':
            form = SetNewPasswordForm(request.POST)
            if form.is_valid():
                user.set_password(form.cleaned_data['new_password'])
                user.save()
                return redirect('blog:password_reset_complete')
        else:
            form = SetNewPasswordForm()
        return render(request, 'partials/password_reset_confirm.html', {'form': form, 'validlink': validlink})
    else:
        return render(request, 'partials/password_reset_confirm.html', {'validlink': validlink})


def password_reset_done_view(request):
    return render(request, 'partials/password_reset_done.html')


def password_reset_complete_view(request):
    return render(request, 'partials/password_reset_complete.html')


def register(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'partials/congratulations.html', {'user': user})
    else:
        form = UserRegister()
    return render(request, 'partials/register.html', {'form': form})


def user_edit(request):
    try:
        account = request.user.account
    except ObjectDoesNotExist:
        account = Account.objects.create(user=request.user)

    if request.method == "POST":
        form = UserEdit(request.POST, instance=request.user)
        account_form = AccountEdit(request.POST, request.FILES, instance=account)
        if form.is_valid() and account_form.is_valid():
            form.save()
            account_form.save()
            return redirect('/')

    else:
        form = UserEdit(instance=request.user)
        account_form = AccountEdit(instance=account)

    context = {
        'user_form': form,
        'account_form': account_form,
        'account': account,
    }
    return render(request, 'partials/edit_information.html', context)

blog/templates/blog/Help.html
{% extends 'parent/Base.html' %}
{% block title %} Help {% endblock %}

{% block content %}
<style>
  .help-container {
    max-width: 800px;
    margin: 3rem auto;
    background: #eef6fb;
    padding: 2.5rem 3rem;
    border-radius: 12px;
    box-shadow: 0 6px 18px rgba(0, 122, 204, 0.15);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #222;
    line-height: 1.7;
  }

  .help-container h1 {
    text-align: center;
    color: #007acc;
    font-weight: 700;
    margin-bottom: 1.8rem;
  }

  .help-container p {
    font-size: 1.1rem;
    margin-bottom: 1.4rem;
  }

  .help-container ul {
    list-style: inside disc;
    margin-left: 1rem;
    margin-bottom: 1.6rem;
    font-size: 1.05rem;
  }

  .help-container ul li {
    margin-bottom: 0.8rem;
  }

  .help-container a {
    display: inline-block;
    margin-top: 2rem;
    padding: 10px 22px;
    background-color: #007acc;
    color: white;
    text-decoration: none;
    border-radius: 8px;
    font-weight: 600;
    transition: background-color 0.3s ease;
  }

  .help-container a:hover {
    background-color: #005a99;
  }
</style>

<div class="help-container">
  <h1>Project Help</h1>
  <p>
    To use this system, you first need to register an account. After logging in, you can access your profile, manage connected devices, leave comments, and use other features.
  </p>
  <ul>
    <li>To update your personal information, go to the Profile section.</li>
    <li>If you experience any issues, you can contact us via the "Contact Us" section.</li>
    <li>You can share your feedback in the Comments section.</li>
  </ul>
  <p>
    If you have a question that is not covered here, please reach out to our support team.
  </p>
  <p><a href="{% url 'blog:profile' %}">Back</a></p>
</div>
{% endblock %}

blog/templates/blog/detail_book.html
{% extends 'parent/Base.html' %}
{% block title %} Detail Book {% endblock %}

{% block content %}
<style>
  .detail-book {
    max-width: 900px;
    margin: 2rem auto;
    background: #fff;
    padding: 25px 30px;
    border-radius: 15px;
    box-shadow: 0 10px 25px rgba(0,0,0,0.1);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #333;
  }

  /* Flex container for info and main image */
  .detail-main {
    display: flex;
    gap: 30px;
    align-items: flex-start;
    flex-wrap: wrap;
  }

  /* Left: book info */
  .book-info {
    flex: 1 1 55%;
    min-width: 280px;
  }
  .book-info h2 {
    margin-bottom: 20px;
    color: #007acc;
    font-weight: 700;
  }
  .book-info p {
    margin: 10px 0;
    font-size: 1.1rem;
    line-height: 1.4;
  }
  .book-info strong {
    color: #005a8c;
  }

  /* Right: main book image */
  .book-image {
    flex: 1 1 40%;
    min-width: 200px;
    max-width: 350px;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 8px 20px rgba(0,123,204,0.15);
  }
  .book-image img {
    width: 100%;
    height: auto;
    display: block;
    border-radius: 12px;
  }

  /* Download & file links */
  .download-links {
    margin-top: 20px;
    display: flex;
    gap: 15px;
  }
  .download-link {
    background-color: #007acc;
    color: white;
    padding: 10px 18px;
    border-radius: 30px;
    text-decoration: none;
    font-weight: 600;
    box-shadow: 0 5px 15px rgba(0,123,204,0.4);
    transition: background-color 0.3s ease, box-shadow 0.3s ease;
  }
  .download-link:hover {
    background-color: #005a8c;
    box-shadow: 0 8px 20px rgba(0,90,140,0.7);
  }
  .no-file {
    font-style: italic;
    color: #999;
    margin-top: 15px;
  }

  /* Gallery of other images */
  .book-gallery {
    margin-top: 30px;
    display: flex;
    gap: 15px;
    flex-wrap: wrap;
    justify-content: flex-start;
  }
  .book-gallery img {
    width: 120px;
    height: 160px;
    object-fit: cover;
    border-radius: 12px;
    box-shadow: 0 6px 18px rgba(0,0,0,0.1);
    transition: transform 0.3s ease;
    cursor: pointer;
  }
  .book-gallery img:hover {
    transform: scale(1.05);
    box-shadow: 0 10px 25px rgba(0,123,204,0.3);
  }

  /* Comment Section */
  .comment-section {
    max-width: 900px;
    margin: 40px auto 60px;
    background: #f9fbfd;
    padding: 25px 30px;
    border-radius: 15px;
    box-shadow: 0 8px 20px rgba(0,123,204,0.1);
  }
  .comment-title {
    font-weight: 700;
    color: #007acc;
    margin-bottom: 20px;
  }

  .comment-form .form-group {
    margin-bottom: 18px;
  }
  .comment-label {
    display: block;
    font-weight: 600;
    margin-bottom: 6px;
  }
  .form-input, .form-textarea {
    width: 100%;
    padding: 10px 15px;
    font-size: 1rem;
    border: 1.8px solid #ccc;
    border-radius: 8px;
    transition: border-color 0.3s ease;
  }
  .form-input:focus, .form-textarea:focus {
    outline: none;
    border-color: #007acc;
    box-shadow: 0 0 8px rgba(0, 122, 204, 0.3);
  }
  .form-textarea {
    resize: vertical;
    min-height: 100px;
  }

  .comment-submit {
    background-color: #007acc;
    color: white;
    padding: 12px 28px;
    border: none;
    border-radius: 30px;
    font-weight: 700;
    cursor: pointer;
    transition: background-color 0.3s ease, box-shadow 0.3s ease;
  }
  .comment-submit:hover {
    background-color: #005a8c;
    box-shadow: 0 8px 20px rgba(0,90,140,0.7);
  }

  .comment-list {
    margin-top: 30px;
  }
  .comment-count {
    font-weight: 700;
    margin-bottom: 10px;
    color: #007acc;
  }
  .single-comment {
    background: white;
    padding: 15px 20px;
    border-radius: 12px;
    margin-bottom: 15px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.07);
  }
  .comment-author {
    font-weight: 700;
    color: #005a8c;
    margin-bottom: 8px;
  }
  .comment-body {
    font-style: italic;
    color: #444;
    line-height: 1.4;
  }
  .no-comments {
    font-style: italic;
    color: #999;
    text-align: center;
    padding: 25px 0;
  }

  /* Responsive */
  @media (max-width: 768px) {
    .detail-main {
      flex-direction: column;
    }
    .book-image, .book-info {
      flex: 1 1 100%;
      max-width: 100%;
    }
    .book-gallery img {
      width: 100px;
      height: 130px;
    }
  }
</style>

<form method="get" action="{% url 'blog:search' %}" style="max-width:900px;margin: 0 auto 30px; display:flex; gap:10px;">
    <input type="text" name="query" placeholder="Search books..." style="flex:1; padding:10px 15px; font-size:1rem; border: 1.8px solid #ccc; border-radius: 8px;" />
    <input type="submit" value="Search" style="background:#007acc; color:#fff; border:none; padding: 10px 20px; border-radius: 8px; cursor:pointer; font-weight:700; transition: background-color 0.3s ease;" />
</form>

<div class="detail-book">
  <div class="detail-main">
    <div class="book-info">
      <h2>Detail Book</h2>
      <p><strong>Title:</strong> {{ book.title }}</p>
      <p><strong>Description:</strong> {{ book.description }}</p>
      <p><strong>Pages:</strong> {{ book.num_pages }}</p>
      <p><strong>Publisher:</strong> {{ book.publisher }}</p>
      <p><strong>Price:</strong> {{ book.price }}</p>
      <p><strong>Language:</strong> {{ book.language }}</p>
      <p><strong>Author:</strong> {{ book.author }}</p>
      <p><strong>Published:</strong> {{ book.publish|date:"Y/m/d" }}</p>

      <div class="download-links">
        {% if book.file %}
          <a href="{{ book.file.url }}" class="download-link" target="_blank" rel="noopener">Show file</a>
          <a href="{% url 'blog:download_book' book.id %}" class="download-link">Download file</a>
        {% else %}
          <p class="no-file">There is no file to download.</p>
        {% endif %}
      </div>
    </div>

    <div class="book-image">
      {% if book.images.all %}
        <img src="{{ book.images.all.0.image.url }}" alt="{{ book.title }}">
      {% else %}
        <img src="https://via.placeholder.com/350x460?text=No+Image" alt="No image available">
      {% endif %}
    </div>
  </div>

  {% if book.images.count > 1 %}
  <div class="book-gallery">
    {% for img in book.images.all %}
      <img src="{{ img.image.url }}" alt="Book image {{ forloop.counter }}">
    {% endfor %}
  </div>
  {% endif %}
</div>

<hr>

<div class="comment-section">
  <h2 class="comment-title">Comments</h2>
  <form method="post" action="{% url 'blog:comment_book' book.id %}" class="comment-form">
    {% csrf_token %}
    <div class="form-group">
      <label for="name" class="comment-label">Name:</label>
      <input type="text" name="name" class="form-input" placeholder="Enter your name" {% if form.name.value %} value="{{ form.name.value }}" {% endif %}>
    </div>

    <div class="form-group">
      <label for="body" class="comment-label">Comment:</label>
      <textarea name="body" class="form-textarea" placeholder="Write your comment here..."></textarea>
    </div>

    <input type="submit" value="Send" class="comment-submit">
  </form>

  <div class="comment-list">
    <p class="comment-count">Number of Comments: {{ comment.count }}</p>
    <hr>
    {% for cm in comment %}
      <div class="single-comment">
        <p class="comment-author">{{ cm.name }}</p>
        <p class="comment-body">{{ cm.body }}</p>
      </div>
    {% empty %}
      <p class="no-comments">No Comments</p>
    {% endfor %}
  </div>
</div>

{% endblock %}

blog/templates/blog/password_change_done.html
{% extends 'parent/Base.html' %}
{% block title %} Login {% endblock %}

{% block content %}
<style>
  .login-container {
    max-width: 360px;
    margin: 5rem auto;
    padding: 2.5rem 2rem;
    background: #f0f4f8;
    border-radius: 12px;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
    text-align: center;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #222;
  }

  .login-container h1 {
    font-weight: 700;
    color: #007acc;
    margin-bottom: 1.5rem;
    font-size: 2.2rem;
  }

  .login-container a {
    display: inline-block;
    padding: 10px 25px;
    background-color: #007acc;
    color: #fff;
    border-radius: 8px;
    font-weight: 600;
    text-decoration: none;
    box-shadow: 0 4px 10px rgba(0, 122, 204, 0.4);
    transition: background-color 0.3s ease, box-shadow 0.3s ease;
    user-select: none;
  }

  .login-container a:hover {
    background-color: #005a99;
    box-shadow: 0 6px 14px rgba(0, 90, 153, 0.7);
  }
</style>

<div class="login-container">
  <h1>Good</h1>
  <a href="{% url 'blog:profile' %}">Back</a>
</div>
{% endblock %}

blog/templates/blog/profile.html
{% extends 'parent/Base.html' %}
{% block title %}Profile{% endblock %}

{% block content %}
<style>
    /* کانتینر پروفایل */
    .profile-container {
        max-width: 700px;
        margin: 2.5rem auto;
        background: linear-gradient(145deg, #e0f7fa, #ffffff);
        border-radius: 25px;
        padding: 2.5rem 3rem;
        box-shadow: 0 15px 40px rgba(0, 128, 255, 0.15);
        animation: fadeInUp 0.8s ease-out;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    /* انیمیشن ورود */
    @keyframes fadeInUp {
        from {
            opacity: 0;
            transform: translateY(40px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    /* تیتر پروفایل */
    h2 {
        text-align: center;
        color: #007acc;
        margin-bottom: 2rem;
        font-weight: 700;
        letter-spacing: 1.2px;
        animation: fadeIn 1s ease-in;
    }

    @keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
    }

    /* عکس پروفایل */
    .profile-photo {
        display: block;
        margin: 0 auto 2rem auto;
        width: 180px;
        height: 180px;
        border-radius: 50%;
        object-fit: cover;
        box-shadow: 0 8px 25px rgba(0, 122, 204, 0.4);
        border: 5px solid #00bcd4;
        transition: transform 0.4s ease;
    }
    .profile-photo:hover {
        transform: scale(1.05);
    }

    /* اطلاعات کاربر */
    .user-info p {
        font-size: 1.15rem;
        color: #005a8c;
        margin: 0.6rem 0;
        padding-left: 12px;
        border-left: 3px solid #00bcd4;
        opacity: 0;
        animation: fadeIn 0.7s ease forwards;
    }

    /* تاخیر انیمیشن در نمایش اطلاعات */
    .user-info p:nth-child(1) { animation-delay: 0.3s; }
    .user-info p:nth-child(2) { animation-delay: 0.5s; }
    .user-info p:nth-child(3) { animation-delay: 0.7s; }
    .user-info p:nth-child(4) { animation-delay: 0.9s; }
    .user-info p:nth-child(5) { animation-delay: 1.1s; }
    .user-info p:nth-child(6) { animation-delay: 1.3s; }
    .user-info p:nth-child(7) { animation-delay: 1.5s; }
    .user-info p:nth-child(8) { animation-delay: 1.7s; }
    .user-info p:nth-child(9) { animation-delay: 1.9s; }

    hr {
        margin: 2rem 0;
        border: none;
        border-top: 1.5px solid #00bcd4;
        opacity: 0.7;
        animation: fadeIn 0.9s ease-in;
    }

    /* بخش لینک‌ها */
    .link-section p {
        font-weight: 700;
        color: #007acc;
        margin-bottom: 0.6rem;
        letter-spacing: 0.5px;
    }

    a {
        display: inline-block;
        margin: 0.35rem 0;
        text-decoration: none;
        color: #0288d1;
        font-weight: 600;
        transition: color 0.3s ease, transform 0.3s ease;
        animation: fadeIn 0.8s ease;
    }

    a:hover {
        color: #00bcd4;
        transform: scale(1.1);
    }

    ul {
        padding-left: 1.4rem;
    }

    li {
        margin: 0.35rem 0;
    }

    /* واکنش‌گرایی برای موبایل */
    @media (max-width: 480px) {
        .profile-container {
            padding: 2rem 1.5rem;
            margin: 1.5rem 1rem;
        }
        .user-info p {
            font-size: 1rem;
        }
        .profile-photo {
            width: 140px;
            height: 140px;
            margin-bottom: 1.5rem;
        }
    }
</style>

<div class="profile-container">
    <h2>Profile</h2>

    {% if user.account.photos %}
        <img src="{{ user.account.photos.url }}" alt="Profile photo" class="profile-photo">
    {% endif %}

    {% if user.is_authenticated %}
        <div class="user-info">
            <p><strong>User name:</strong> {{ user.username }}</p>
            <p><strong>First name:</strong> {{ user.first_name }}</p>
            <p><strong>Last name:</strong> {{ user.last_name }}</p>
            <p><strong>Job:</strong> {{ user.account.job }}</p>
            <p><strong>Birth:</strong> {{ user.account.birth }}</p>
            <p><strong>Bio:</strong> {{ user.account.bio }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Last login:</strong> {{ user.last_login }}</p>
            <p><strong>Date joined:</strong> {{ user.date_joined }}</p>
        </div>
    {% endif %}

    <hr>

    <div class="link-section">
        <p>My home library:</p>
        <a href="{% url 'blog:my_books' %}">My Books</a>
    </div>

    <hr>

    <div class="link-section">
        <p>Change password:</p>
        <a href="{% url 'blog:password_change' %}">Change Password</a>
    </div>

    <hr>

    <div class="link-section">
        <p>Edit Profile</p>
        <a href="{% url 'blog:user_edit' %}">Edit Profile</a>
    </div>

    <hr>

    <div class="link-section">
        <p>Site Policies</p>
        <ul>
            <li><a href="{% url 'blog:about' %}">About Project</a></li>
            <li><a href="{% url 'blog:help' %}">Help</a></li>
            <li><a href="{% url 'blog:terms' %}">Terms of Use</a></li>
        </ul>
    </div>
</div>
{% endblock %}